version: "3.8"

services:
  db:
    image: mariadb:10.6.4
    container_name: "users_database"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    networks:
      - nuboverflow

  #Good little testing UI - recommend turning off for a PROD release.
  adminer:
    image: adminer
    container_name: "users_database-adminer"
    restart: always
    ports:
      - 8080:8080
    networks:
      - nuboverflow

  api:
    build: .
    image: millbj92/nuboverflow-users:v1
    restart: always
    container_name: "users_microservice"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - nuboverflow

networks:
  nuboverflow:
    driver: bridge